Gandalan.IDAS.WebApi.Data/DTOs/Produktion/BearbeitungDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialbedarfDTO.cs
=> Add missing properties to BearbeitungDTO & MaterialbedarfDTO

Gandalan.IDAS.Client.Contracts/Contracts/DataServices/IAblageService.cs, Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/IAblageManager.cs, Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ILabelPrinter.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/AblageDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/AblageFachDTO.cs
- Erweiterung ILabelPrinter um die PrintCustom Methode
- Hinzufügen von IAblageService, IAblageManager, AblageDTO, AblageFachDTO
=> Anpassungen für IBOS3 Ablageverwaltung

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/IEtikettenDruckService.cs
Erweiterung IEtikettenDruckService um Printmethode mit Liste von EtikettDTOs
=> Erweiterung IEtikettenDruckService

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/IBOS1ImportRoutinen.cs, Gandalan.IDAS.WebApi.Data/DTOs/Belege/BaseListItemDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Belege/BestellungListItemDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Belege/MaterialBestellungListItemDTO.cs
Neue Baseclass eingeführt, sowie MaterialbestellungenListItemDTO. BestellungListItemDTO ist nun von BaseListItemDTO abgeleitet
=> Neu: MaterialBestellungen

Gandalan.IDAS.Client.Contracts/Contracts/DataServices/ILagerbestandService.cs, Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ILabelPrinter.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/AblageDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/LagerbestandDTO.cs
Labeldruck:
- Anpassung ILabelPrinter, damit auch der GDI Printer über die PrintCustom Methode angesteuert werden kann (mit Übergabe eines Template Objekts)
- Erweiterung AblageDTO um Kürzel für die Anzeige auf dem Etikett
Bestandsverwaltung
- LaberbestandDTO: DTO für die Erfassung der Lagerbestände
- ILagerbestandService: Interface für das Data Layer der Bestandsverwaltung
=> Anpassungen Labeldruck und Lagerbestand

Gandalan.IDAS.WebApi.Data/DTOs/Produktion/AblageDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/AblageFachDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/LagerbestandDTO.cs
Anpassung an DTOs für Übernahme ins Backend
=> Anpassung an EWU DTOs

Gandalan.IDAS.WebApi.Data/DTOs/Produktion/ProduktionsDatenDTO.cs
GetSaegeliste():
Bedingung auf Zuschnittlänge > 0 hinzugefügt, da ein Zuschnitt mit Länge 0 keinen Sinn ergibt (und zu Problemen führt).
GetMaterialbedarf():
Bedingung entsprechend ebenfalls erweitert (negierte Saegeliste)
=> ProduktionsDatenDTO

Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialBeschaffungsJobDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialbedarfDTO.cs
Anpassungen an MaterialBedarfDTO und MaterialBeschaffunsJobDTO für die Beschichtung
=> Anpassungen für Beschichtung

Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialItemDTO.cs
Übernahme MaterialPCode in MaterialItemDTO
=> Übernahme MaterialPCode in MaterialItemDTO

Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialBeschaffungsJobDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialItemDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialbedarfDTO.cs
KatalogArtikelArt in MaterialbedarfDTO, MaterialItemDTO und MaterialBeschaffungsJobDTO eingefügt
=> KatalogArtikelArt in MaterialbedarfDTO, MaterialItemDTO und MaterialBeschaffungsJobDTO eingefügt

Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialBeschaffungsJobDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialBeschaffungsJobStatiDTO.cs
FolgeJob in MaterialBeschaffungsJob eingeführt
=> FolgeJob in MaterialBeschaffungsJob eingeführt

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/LagerbestandWebRoutinen.cs
Lagerbuchung in die LagerbestandWebRoutinen aufgenommen
=> Lagerbuchung

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/MaterialBestellungWebRoutinen.cs
Methode für MaterialbeschaffungsJob Status Update über den MaterialBestellungStatusController hinzugefügt.
=> Statusrückmeldung Beschichtung

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/IAblageManager.cs
=> Anpassung IAblageManager

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/IEtikettenDruckAufbereitung.cs, Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/IEtikettenDruckService.cs, Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ILabelPrinter.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/EtikettDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/EtikettDatenDTO.cs
=> Änderungen EtikettenDruck

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ISaegeDatenGenerator.cs, Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ISaegeDatenSender.cs, Gandalan.IDAS.Client.Contracts/Contracts/Report/ISerienPacklisteAufbereitenService.cs, Gandalan.IDAS.Client.Contracts/Contracts/Report/ISerienSaegelisteAufbereitenService.cs, Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienPacklisteDataDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienPacklisteGruppeDataDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienPacklisteGruppeItemDataDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienSaegelisteDataDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienSaegelisteProfilgruppeDataDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienSaegelistenProfilgruppeSchnittDataDTO.cs
Umzug Sägelisten- und Packlistenreport
=> Umzug Sägelisten- und Packlistenreport

Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienSaegelisteProfilgruppeDataDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Reports/SerienSaegelistenProfilgruppeSchnittDataDTO.cs
Erweiterung SaegeListenDaten für Sägedateierzeugung
=> Erweiterung SaegeListenDaten für Sägedateierzeugung

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/IEtikettenDruckAufbereitung.cs
Umstellung IEtikettenDruckAufbereitung auf asynchrone Verarbeitung
=> Umstellung IEtikettenDruckAufbereitung auf async

Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialBeschaffungsJobDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialItemDTO.cs, Gandalan.IDAS.WebApi.Data/DTOs/Produktion/MaterialbedarfDTO.cs
Added "ProfilGedrehtSaegen" to MaterialbedarfDTO, MateralItemDTO, MaterialBeschaffungsJobDTO
=> Added "ProfilGedrehtSaegen" 

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/AVWebRoutinen.cs
AVWebRoutinen - GetBelegPositionAVById hinzugefügt
=> AVWebRoutinen - GetBelegPositionAVById hinzugefügt

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/SerienMaterialEditWebRoutinen.cs, Gandalan.IDAS.WebApi.Data/DTOs/AV/SerienMaterialEditDTO.cs
AddOrUpdate SerienMaterial auf SerienMaterialEditDTO umgestellt
=> AddOrUpdate SerienMaterial auf SerienMaterialEditDTO umgestellt

Gandalan.IDAS.WebApi.Data/Util/gSQL/gSQLExporter.cs
Fix `NullReferenceException` - for example when we are playing with modified JSON - just like in our IBOS2 microservice integration tests ;)
=> Fix `NullReferenceException`

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ISchnittOptimierung.cs
https://dev.azure.com/gandalan/IDAS/_workitems/edit/5925
Don't know if I chosen the right place
=> #5925 Add MaterialbedarfCutOptimization

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ISchnittOptimierung.cs
Change `ISchnittOptimierung` after merging `5925_cutOptimization` branch to master
=> Change `ISchnittOptimierung`

Gandalan.IDAS.WebApi.Client/DTOs/Produktion/EtikettDTO.cs
=> Introduce `EtikettenProfilVorbiegen` in `EtikettDTO`

Gandalan.IDAS.WebApi.Client/Contracts/ProduktionsServices/ISaegeDatenSender.cs, Gandalan.IDAS.WebApi.Client/DTOs/Produktion/SaegeKonfigurationDTO.cs
#6822 - unterschiedliche Ausgabeverzeichnisse für die Sägedateien
=> #6822 - unterschiedliche Ausgabeverzeichnisse für die Sägedateien

Gandalan.IDAS.WebApi.Client/DTOs/Settings/ProduktionsSettingsDTO.cs
Settings für Etiketten hinzugefügt
=> Settings für Etiketten hinzugefügt

Gandalan.IDAS.WebApi.Client/Contracts/ProduktionsServices/ISaegeDatenSender.cs, Gandalan.IDAS.WebApi.Client/DTOs/Produktion/SaegeKonfigurationDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Settings/ProduktionsSettingsDTO.cs
Parameteranpassung SaegedatenSender; Erweiterung SaegeKonfiguration DTO
=> Parameteranpassung SaegedatenSender; Erweiterung SaegeKonfiguration DTO

Gandalan.IDAS.WebApi.Client/DTOs/Settings/ProduktionsSettingsDTO.cs
SägelisteEtiketten Sortierung mit Positionsbezug / HaendlerNameAufEtikett
=> SägelisteEtiketten Sortierung mit Positionsbezug / HaendlerNameAufEtikett

.github/workflows/build-and-publish.yml, .github/workflows/publish-weblibs.yml
Do not run GH Actions for forks
See: https://github.com/prisma/prisma-examples/pull/1999
=> Run workflows only for Gandalan

.github/workflows/build-and-publish.yml, Gandalan.IDAS.Crypto/Gandalan.IDAS.Crypto.csproj, Gandalan.IDAS.Libs.sln, Gandalan.IDAS.Logging/Gandalan.IDAS.Logging.csproj, Gandalan.IDAS.WebApi.Client.Wpf/Gandalan.IDAS.WebApi.Client.Wpf.csproj, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
- fix Visual Studio build
- switch from `dotnet pack` to `nuget pack` (Azure DevOps style). Seems like `dotnet pack xxx.csproj -p:NuspecFile=path/GDL.xxx.nuspec` doesn't work
=> Fix VS build. Switch to `nuget pack`

.github/workflows/publish-weblibs.yml, WebLibs/package-lock.json, WebLibs/package.json
Works for me: https://github.com/Saibamen/idas-client-libs/runs/6587935329?check_suite_focus=true
=> Fix NPM workflow

.github/workflows/build-and-publish.yml
Looks like we have two this same `.nupkg` files...
=> `--skip-duplicate` for `dotnet nuget push` command

Gandalan.IDAS.WebApi.Client/Util/gSQL/gSQLInhalt.cs, Gandalan.IDAS.WebApi.Client/Util/gSQL/gSQLSektion.cs
First Item can be empty.
Also fix possible NRE for `GetSektion()`
=> Fix NRE in `gSQLSektion.GetItem()`

WebLibs/components/GanTable.svelte, WebLibs/package-lock.json, WebLibs/package.json
=> Svelte table + update dependencies

WebLibs/package.json
See: https://stackoverflow.com/a/41307319/886915
=> Add `typings` into `package.json`

.github/workflows/check-weblibs.yml, .github/workflows/publish-weblibs.yml, WebLibs/components/Datepicker.svelte, WebLibs/components/Inputbox.svelte, WebLibs/declarations.d.ts, WebLibs/jsconfig.json, WebLibs/package-lock.json, WebLibs/package.json
=> Add `svelte-check` and fix hints and warnings

.github/workflows/check-NuGet-Libs.yml
`dotnet restore`, `dotnet build` and `nuget pack` without publish
=> Check NuGet libs on Pull Request

Gandalan.IDAS.WebApi.Client.Wpf/Gandalan.IDAS.WebApi.Client.Wpf.csproj, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
And fix copy-paste bug introduced in https://github.com/gandalan/idas-client-libs/pull/152
=> Fix debugging local NuGet package in i3 Client

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/FilterWebRoutinen.cs, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/VorgangWebRoutinen.cs
`Archivierung` and `FilterWebRoutinen`
=> Fix few API endpoints for .NET 6 routings

Gandalan.IDAS.Logging/Logging/Logger.cs
Debug class has its own condition
=> Debug.WriteLine without #if DEBUG

Gandalan.IDAS.WebApi.Client/RESTClientBase.cs
=> Follow-up of 092e806

.github/workflows/conflicts.yml, .github/workflows/publish-weblibs.yml
https://github.com/marketplace/actions/label-conflicting-pull-requests
Example: https://github.com/yairm210/Unciv/pull/7890
=> Add GH Action with `eps1lon/actions-label-merge-conflict`

WebLibs/api/IDAS.js
Now IDAS works with authToken ("t" parameter) and JWT ("j" parameter).
It requires IDAS/JWTFromAuthToken to work (LoginJwtController.Refresh() work for both refreshToken and authToken).
I also made authorization login moved into IDASFactory.create()
=> IDAS works with "t" (authToken) and "j" (JWT)

Gandalan.IDAS.Contracts/ChangeTracking/IVersionable.cs, Gandalan.IDAS.Contracts/IKategorieBrowsable.cs, Gandalan.IDAS.Contracts/Repository/IRepository.cs, WebLibs/api/RESTClient.js
Addendum to https://github.com/gandalan/idas-client-libs/pull/201
=> GDL.IDAS.Contracts: Tabs to spaces + use Axios instance for baseURL

.github/workflows/build-and-publish.yml
https://github.com/fregante/release-with-changelog#deprecated
Release:
=> Replace deprecated `release-with-changelog` action

.github/workflows/build-and-publish.yml, .github/workflows/check-NuGet-Libs.yml, .github/workflows/check-weblibs.yml, .github/workflows/publish-weblibs.yml
Add workflow_dispatch trigger for all workflows (except`conflicts.yml`)
Documentation: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
=> Add `workflow_dispatch` trigger for all workflows

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/AVWebRoutinen.cs
Für neuen Endpunkt zum Speichern aus dem Serien zuordnen Tab
=> #8738 AVWebRoutinen BelegPositionenSerienZuordnen

.github/workflows/conflicts.yml
=> Better job name for Maintenance

Gandalan.IDAS.WebApi.Client/Contracts/AV/ISerienPositionsItemHelper.cs, Gandalan.IDAS.WebApi.Client/Contracts/InteractionContracts.cs, Gandalan.IDAS.WebApi.Client/Contracts/Vorgaenge/IExtendedTabControl.cs
Bool Rückgabewert in OnBeforeSave zum Abbrechen
~~ISerienPositionsItemHelper cleanup~~
IExtendedTabControl um angepasste TabControls zu markieren (benötigt für Hinweis-Punkt an TabControl in I3)
=> Diverse Änderung in Bezug auf FreigabeTimer

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/NotifyWebRoutinen.cs, Gandalan.IDAS.WebApi.Client/Contracts/DataServices/INachrichtenService.cs, Gandalan.IDAS.WebApi.Client/DTOs/Nachrichten/NachrichtenDTO.cs, Gandalan.IDAS.WebApi.Client/Tiles/ITileItem.cs
=> Extract NachrichtenDTO, add INachrichtenService, Update ITileItem

Gandalan.IDAS.Contracts/Token/JwtTokenService.cs, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs
Include token "type" into the token; allow "refreshToken" empty for "Service" tokens
=> Include token "type"

Gandalan.IDAS.WebApi.Client.Wpf/Dialogs/LoginWindow_v2.xaml.cs
Login window for full login scenario was not reflecting env change from the dropdown
=> LoginWindow_v2: reflect change to env as selected from the dropdown

Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
Changelog for `Newtonsoft.Json` : https://github.com/JamesNK/Newtonsoft.Json/releases
Changelog for `System.IdentityModel.Tokens.Jwt` : https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases
=> Update `Newtonsoft.Json` and `System.IdentityModel.Tokens.Jwt`

Gandalan.IDAS.WebApi.Client/Contracts/IValidator.cs, Gandalan.IDAS.WebApi.Client/Contracts/UIServices/IKundeEditorModul.cs, Gandalan.IDAS.WebApi.Client/Contracts/UIServices/IOverlayNotify.cs
=> #8890 IValidator CancelledSave Event

Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
Changelog: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases
=> NuGet update

Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
This reverts commit 0da136611fa7ad465d6e188cda655b3cd6c87e6a.
=> Revert "Merge pull request #248 from Saibamen/nuget"

Gandalan.IDAS.Logging/Logging/Logger.cs
1. Use `yyyy-MM-dd` date format for better file sorting experience (see screenshot for current state)
2. Log messages to both console and debug - console messages will be visible in Azure logs
3. Log full exception info with standard format - all stacktrace, inner exceptions, inner stack trace etc
=> Logger improvements

Gandalan.IDAS.Contracts/GDL.IDAS.Contracts.nuspec, Gandalan.IDAS.Crypto/GDL.IDAS.Crypto.nuspec, Gandalan.IDAS.Logging/GDL.IDAS.Logging.nuspec, Gandalan.IDAS.WebApi.Client.Wpf/GDL.IDAS.WebApi.Client.Wpf.nuspec, Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec
Related: https://github.com/gandalan/idas-client-libs/pull/260
=> Add `README.md` to public packages

WebLibs/.eslintrc.cjs, WebLibs/components/DataGrid.svelte, WebLibs/package-lock.json, WebLibs/package.json
=> Update WebLibs dependencies

Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/v6.32.0
=> Update System.IdentityModel.Tokens.Jwt (performance fix)

.github/workflows/publish-weblibs.yml
=> Fix commit-message for `phips28/gh-action-bump-version action`

.github/workflows/build-and-publish.yml
Related: https://github.com/gandalan/idas-client-libs/pull/271 https://github.com/gandalan/idas-client-libs/pull/270
=> Fix nuget publish

Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
=> Update `System.IdentityModel.Tokens.Jwt` to 6.32.3

.editorconfig, Gandalan.IDAS.Libs.sln, Gandalan.IDAS.Logging/Logging/Logger.cs, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/FarbKuerzelGruppenWebRoutinen.cs, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/PrintWebRoutinen.cs, Gandalan.IDAS.WebApi.Client/DTOs/Belege/BelegDruckDTO.cs, Gandalan.IDAS.WebApi.Client/HttpClientFactory.cs, Gandalan.IDAS.WebApi.Client/Settings/ConnectHub.cs, Gandalan.IDAS.WebApi.Client/Settings/WebApiConfigurations.cs, Gandalan.IDAS.WebApi.Client/Settings/WebApiSettings.cs, Gandalan.IDAS.WebApi.Client/Util/PropertyValueCollection.cs, Gandalan.IDAS.WebApi.Client/Util/gSQL/gSQLExporter.cs
From: https://github.com/dotnet/aspnetcore
Disabled rules: [dotnet_sort_system_directives_first](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/dotnet-formatting-options), [CA1018](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1018), [CA1305](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1305), [CA1507](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1507), [CA1805](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1805), [CA2007](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA2007), [CA2208](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA2208), …
=> EditorConfig from dotnet/aspnetcore repo

.editorconfig, Gandalan.IDAS.WebApi.Client/Contracts/Report/IReport.cs, Gandalan.IDAS.WebApi.Client/Contracts/Vorgaenge/IVorgangCommand.cs, Gandalan.IDAS.WebApi.Client/DTOs/Belege/BelegDruckDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Belege/BelegartWechselDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Belege/KapazitaetsvorgabenDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Kunden/KontaktDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Mandanten/MandantDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Rechnung/SammelrechnungDruckDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Reports/SerienSaegelisteDataDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Settings/ProduktionProduktfamilieSettingsDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Settings/ProduktionsSettingsDTO.cs, Gandalan.IDAS.WebApi.Client/Printing/ProduktionsLieferscheinData.cs, Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
Enable performance warning [CA1805](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1805) (Do not initialize unnecessarily)
Disable style warning [IDE0161](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0160-ide0161) (Convert to file-scoped namespace)
Related: https://github.com/gandalan/idas-client-libs/pull/278
=> Enable warning CA1805. Disable IDE0161

.editorconfig, Gandalan.IDAS.WebApi.Client.Wpf/Controls/LargeHeaderControl.xaml.cs, Gandalan.IDAS.WebApi.Client.Wpf/Dialogs/LoginWindowViewModel_v2.cs, Gandalan.IDAS.WebApi.Client.Wpf/Dialogs/PasswordResetDialog.xaml.cs, Gandalan.IDAS.WebApi.Client.Wpf/Dialogs/SetupDialog.xaml.cs, Gandalan.IDAS.WebApi.Client/Contracts/IValidator.cs, Gandalan.IDAS.WebApi.Client/Contracts/UIServices/IAddonCommand.cs, Gandalan.IDAS.WebApi.Client/Contracts/Vorgaenge/IBelegPositionCommand.cs, Gandalan.IDAS.WebApi.Client/Contracts/Vorgaenge/IVorgangCommand.cs, Gandalan.IDAS.WebApi.Client/DTOs/Belege/BelegDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Belege/KapazitaetsvorgabenDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Belege/VorgangDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Benutzer/BenutzerDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Kunden/BeleganschriftDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Kunden/KontaktDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Kunden/ZusatzanschriftDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Mandanten/MandantDTO.cs, Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
We have already disabled this in the IDAS repository.
Remove disabling and enabling CS0067 in code.
Related: #278, #279
=> Disable `CS0067` in EditorConfig

Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
Addendum to https://github.com/gandalan/idas-client-libs/pull/281
To suppress warnings in Docker build etc.
=> No warn for CS0067 in csproj file

Gandalan.IDAS.Contracts/GDL.IDAS.Contracts.nuspec, Gandalan.IDAS.Contracts/Gandalan.IDAS.Contracts.csproj, Gandalan.IDAS.Crypto/GDL.IDAS.Crypto.nuspec, Gandalan.IDAS.Crypto/Gandalan.IDAS.Crypto.csproj, Gandalan.IDAS.Logging/GDL.IDAS.Logging.nuspec, Gandalan.IDAS.Logging/Gandalan.IDAS.Logging.csproj, Gandalan.IDAS.WebApi.Client.Wpf/GDL.IDAS.WebApi.Client.Wpf.nuspec, Gandalan.IDAS.WebApi.Client.Wpf/Gandalan.IDAS.WebApi.Client.Wpf.csproj, Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
=> Remove netstandard and net472

WebLibs/api/IDAS.js, WebLibs/api/authUtils.js, WebLibs/package-lock.json, WebLibs/package.json
Fixes #292 with all updated packages
=> Update all NPM packages

.editorconfig
Sync with https://github.com/dotnet/aspnetcore/commit/b3d1545d8958e5ccc0d988c2181ae4143cff20d8
PR: https://github.com/dotnet/aspnetcore/pull/50854
=> EditorConfig: Sync with b3d1545

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs
Print all Inner Exception Messages in `LoginAsync` and `CheckJwtTokenAsync` + fix naming convention
=> Print all Inner Exception Messages

Gandalan.IDAS.Logging/Logging/L.cs, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs, Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
And fix `CallMethod` value (use `CallerMemberName`)
Remove `BaseUrl` from Exception.Data
=> Print all Exception.Data in logs, also from InnerExceptions

WebLibs/package-lock.json, WebLibs/package.json
ESLint changelog: https://github.com/eslint/eslint/releases/tag/v8.57.0
=> NPM update

Gandalan.IDAS.Libs.sln, nuget_lokal.cmd
And add more files as solution items
=> Fix solution loading bug

Gandalan.IDAS.WebApi.Client/Contracts/IHistorieHelper.cs
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014
=> Fix CS4014 in Functions

Gandalan.IDAS.Contracts/Gandalan.IDAS.Contracts.csproj, Gandalan.IDAS.Crypto/Gandalan.IDAS.Crypto.csproj, Gandalan.IDAS.Logging/Gandalan.IDAS.Logging.csproj, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
=> Remove .NET 7

Gandalan.IDAS.WebApi.Client/Backup/IBackupHelper.cs
Throws build error in isolated Azure Functions
=> Do not use async void for IBackupHelper.

Gandalan.IDAS.Contracts/Gandalan.IDAS.Contracts.csproj, Gandalan.IDAS.Crypto/Gandalan.IDAS.Crypto.csproj, Gandalan.IDAS.Logging/Gandalan.IDAS.Logging.csproj, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
Waiting for Azure Functions to migrate to .NET 8 and isolated workers.
=> Remove .NET 6

.editorconfig
As discussed with Dominik.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using
=> csharp_prefer_simple_using_statement = false

Gandalan.IDAS.WebApi.Client/DTOs/Belege/KapazitaetsvorgabenDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Rechnung/SammelrechnungDruckDTO.cs, Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj, Gandalan.IDAS.WebApi.Client/HttpClientFactory.cs, WebLibs/package-lock.json, WebLibs/package.json
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/8.0.0
=> Update NPM and `System.IdentityModel.Tokens.Jwt` to 8.0.0

Gandalan.IDAS.WebApi.Client/DTOs/Belege/BaseListItemDTO.cs, Gandalan.IDAS.WebApi.Client/Util/IDTOWithApplicationSpecificProperties.cs
=> Switch ASP related calls to extension methods

WebLibs/package-lock.json, WebLibs/package.json
Axios changelog: https://github.com/axios/axios/releases/tag/v1.7.3
=> NPM update + Axios

WebLibs/package-lock.json, WebLibs/package.json
Version 1.7.4 has SSRF fix
https://github.com/advisories/GHSA-8hc4-vh64-cxmj
https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?name=CVE-2024-39338&vector=AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N&version=3.1&source=CISA-ADP
=> Upgrade axios package to 1.7.4

Gandalan.IDAS.Contracts/Gandalan.IDAS.Contracts.csproj
Addendum to https://github.com/gandalan/idas-client-libs/commit/6ba4b666f4e24f24d0b81d919240dd7c7e439f0c
=> Remove leftover net481

Gandalan.IDAS.WebApi.Client/Contracts/UIServices/IProgressNotify.cs
Add paramref to commit 4c68782
FYI @gdl-drw
=> Add `<paramref>`

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs
I hope this will add better stack trace for i3 exceptions in App Insights
=> Add inner exception to ApiException

.github/workflows/build-and-publish.yml, .github/workflows/check-NuGet-Libs.yml
Fixed https://github.com/gandalan/idas-client-libs/pull/434 and https://github.com/gandalan/idas-client-libs/pull/432 actions
=> Use ubuntu-22.04 for Actions with nuget pack command

Gandalan.IDAS.WebApi.Client/Contracts/UIServices/IFernwartungService.cs, Gandalan.IDAS.WebApi.Client/Contracts/UIServices/IHelpProvider.cs, Gandalan.IDAS.WebApi.Client/Contracts/UIServices/INavigationManager.cs, Gandalan.IDAS.WebApi.Client/DTOs/Feedback/FeedbackDTO.cs, Gandalan.IDAS.WebApi.Client/MessageQueue/FeedbackStatusChangeMessagePayload.cs, Gandalan.IDAS.WebApi.Client/Navigation/INavigationGroup.cs
=> 6696 hotline modul

WebLibs/api/fluentAuthBuilder.js
Like in `authUtils`: https://github.com/gandalan/idas-client-libs/blob/master/WebLibs/api/authUtils.js#L37
=> Fluent API: Check if App Token is valid

Gandalan.IDAS.Logging/Logging/Logger.cs
Log messages on Release if app don't have console
=> Add Trace to LogConsoleDebug()

Gandalan.IDAS.WebApi.Client/Contracts/UIServices/INavigationManager.cs, Gandalan.IDAS.WebApi.Client/Navigation/INavigationItem.cs, Gandalan.IDAS.WebApi.Client/Navigation/INavigationSubGroup.cs
+ remove SingleClick from NavItem
=> INavigationSubGroup

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/FileWebRoutinen.cs
See [AB#11998](https://dev.azure.com/gandalan/a6dd0e1c-ebfd-41aa-9f9d-b1a04a1e3bc1/_workitems/edit/11998)
=> Obsolete GetFileListAsync(Guid) and remove not existing PUT StaticFile

Gandalan.IDAS.Contracts/GDL.IDAS.Contracts.nuspec, Gandalan.IDAS.Crypto/GDL.IDAS.Crypto.nuspec, Gandalan.IDAS.Logging/GDL.IDAS.Logging.nuspec, Gandalan.IDAS.WebApi.Client.Wpf/GDL.IDAS.WebApi.Client.Wpf.nuspec, Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec
Go to GitHub project from NuGet.org site and Visual Studio.
=> Add `projectUrl` to nuspecs

WebLibs/package-lock.json, WebLibs/package.json
Use install command from @babel/eslint-parser documentation:
`npm install eslint @babel/core @babel/eslint-parser --save-dev`
https://www.npmjs.com/package/@babel/eslint-parser
=> Add `@babel/core` as dev dependency

Gandalan.IDAS.WebApi.Client/Settings/WebApiConfigurations.cs
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1859
=> Fix CA1859 (performance)

Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
=> Fix nuspec after #472

Gandalan.IDAS.Contracts/Token/JwtTokenService.cs, Gandalan.IDAS.Crypto/HexEncoding.cs, Gandalan.IDAS.Logging/Logging/Logger.cs, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/DataMigrationHistoryWebRoutinen.cs, Gandalan.IDAS.WebApi.Client/DTOs/API/ApiVersionDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Rechnung/SammelrechnungDruckDTO.cs, Gandalan.IDAS.WebApi.Client/Util/AppSpecificPropertiesExtensions.cs, Gandalan.IDAS.WebApi.Client/Util/gSQL/gSQLExporter.cs, Gandalan.IDAS.WebApi.Client/Util/gSQL/gSQLImporter.cs
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305
Not all can be fixed, because some .NET Framework APIs are missing (for example `StringBuilder.Append(IFormatProvider? provider, (...))`).
> [!WARNING]  
> Not tested
=> Fix some CA1305

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/LieferzusageWebRoutinen.cs
New endpoint in Gandalan.IDAS.WebApi.Client/BusinessRoutinen/LieferzusageWebRoutinen.cs
=> 13612 Added endpoint for deleting delivery commitments by SerialGuid
