gandalan/idas-client-libs

Gandalan.IDAS.WebApi.Data/Util/gSQL/gSQLExporter.cs
We want to use `gSQLExporter` from NuGet package for all projects (IDAS repo and IBOS1 microservice already was changed some time ago to use NuGet package).
Yesterday I wanted to apply these changes for IBOS2 legacy and microservice, but our integration tests for microservice was failed. After some time of debugging, I found that order of some properties was changed in `gSQLExporter` from NuGet and we have this logic in IBOS2:
```csharp
for (var i = 0; i < posSektion.Items.Count; i++)
{
var item = posSektion.Items[i];
if (item.Name == "Position_PositionsNummer" ||
item.Name == "Position_LaufendeNummer" ||
item.Name == "Position_Nummer" ||
item.Name == "Position_PositionsGuid")
{
inPos = false;
}
if (item.Name == "Position_PositionsGuid" &&
item.Wert.Equals(posGuid.ToString(), …
```
=> GAN-262: Fix `gSQLExporter` for IBOS1 and IBOS2

Gandalan.IDAS.WebApi.Data/Util/gSQL/gSQLImporter.cs
`gsqlImporter` is used in IBOS2 (Legacy and microservice) and in `IDAS.Backend`
=> Add gSQLImporter

Gandalan.IDAS.Client.Contracts/Contracts/ProduktionsServices/ISchnittOptimierung.cs
Client will need `Laenge` value (`KatalogArtikel.ProfilLaengeMM`)
And try to fix empty result after API call (only 3 classes uses private setters)
=> `ZuschnittStangenInfo`: Public `Laenge` and remove `private` from setters

Gandalan.IDAS.WebApi.Client/DTOs/PositionsDaten/PositionsDatenDTO.cs, Gandalan.IDAS.WebApi.Client/DTOs/Produktion/MaterialbedarfDTO.cs
Bug reported by Rene.
Change `OberFlaeche` to `OberflaecheBezeichnung` in `MaterialbedarfDTO` and `PositionsDatenDTO`.
`OberflaecheBezeichnung` property was introduced in VB6 by Gerhard since 2022.01.11 but is still missing in NuGet
=> Change `OberFlaeche` to `OberflaecheBezeichnung`

.github/workflows/build-and-publish.yml, .github/workflows/publish-weblibs.yml
Create NuGet packages in different directory and change patterns to not upload duplicated files.
Better tag and commit message for WebLibs version bump.
=> Fix NuGet CI - don't push duplicated `nupkg` files

.github/workflows/build-and-publish.yml, Gandalan.IDAS.Crypto/Gandalan.IDAS.Crypto.csproj, Gandalan.IDAS.Logging/Gandalan.IDAS.Logging.csproj, Gandalan.IDAS.WebApi.Client.Wpf/Gandalan.IDAS.WebApi.Client.Wpf.csproj, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
Don't show `CS1591` warnings for Release build like:
```
warning CS1591: Missing XML comment for publicly visible type or member 'IVariantenService.SaveAsync(VarianteDTO)'
```
This will also speed up build a little and fix too long output in GitHub Actions:
```
23397 Warning(s)
0 Error(s)
Time Elapsed 00:00:23.81
```
```
135 Warning(s)
0 Error(s)
Time Elapsed 00:00:21.34
```
=> NoWarn for `CS1591` in Release configuration

.github/workflows/publish-weblibs.yml
Addendum to 4d3a37b1863455b9f2938278e6c157e15a39badc
=> Fix `gh-action-bump-version` parameters

.github/workflows/build-and-publish.yml
Last Pull Request for `publish-weblibs.yml` (https://github.com/gandalan/idas-client-libs/pull/122) created release for NuGet
=> Ignore `publish-weblibs.yml` for NuGet workflow

.github/workflows/publish-weblibs.yml
This same trigger as in NuGet workflow
=> Publish NPM WebLibs after push instead of manually `workflow_dispatch`

WebLibs/index.js
Hopefully it will fix warning from `svelte-check`:
```
Could not find a declaration file for module '@gandalan/weblibs/components/GanTable.svelte'.
'C:/Gandalan/IDAS/Source/Server/IDASDataIntegrityCheck/node_modules/@gandalan/weblibs/components/GanTable.svelte' implicitly has an 'any' type.
```
=> Add GanTable into index

WebLibs/components/GanTable.svelte
Delete `.pr-4` from `classNameCell` and `.cursor-pointer` from `classNameRow`
=> Able to override CSS classes in GanTable

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs, Gandalan.IDAS.WebApi.Client/RESTClientBase.cs, Gandalan.IDAS.WebApi.Client/RESTRoutinen.cs
BaseUrl, Url and CallMethod
Previously, we could not easily see which API call caused `ApiException`:
Now we can see this (this screenshot is not from the final version of this PR, I have problems with VS and I can't build i3 Client anymore...):
=> Fix NRE in `RESTClientBase`. `AddInfoToException()`

.github/workflows/build-and-publish.yml, .github/workflows/check-NuGet-Libs.yml, .github/workflows/publish-weblibs.yml, Gandalan.IDAS.Logging/Logging/L.cs, Gandalan.IDAS.WebApi.Client.Wpf/GDL.IDAS.WebApi.Client.Wpf.nuspec, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs, Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
1. `WebRoutinenBase.cs`: Fix infinite loop
2. `WebRoutinenBase.cs`: Not every exception is caught by i3 Client, so log it here with exception data (URL, caller method)
3. `L.cs`: Sometimes exception have inner exceptions, but is not `AggregateException`
=> Fix infinite loop in `InternalHandleWebException`

WebLibs/api/IDAS.js, WebLibs/api/RESTClient.js, WebLibs/package-lock.json, WebLibs/package.json
Changes in this branch:
* no SSO support (only JWT) (breaking change)
* IDASFactory.create() (no "new IDAS()" calls) (breaking change)
* JWT with "refresh tokens" are now supported
* "refresh tokens" support is now moved into RESTClient.js
* depends on backend changes in https://dev.azure.com/gandalan/IDAS/_git/IDAS/pullrequest/253
=> Store JwtCallback path & authorizeWithJwt() as Promise

WebLibs/api/RESTClient.js
This fixes double slashes and fix requests for .NET Core
Both
- `this.put("/LoginJwt/Refresh"`
- and `this.put("LoginJwt/Refresh"`
will work now
=> Use BaseURL in Axios

WebLibs/api/IDAS.js
With this change we can have only partial settings, without a need to pass all of them. 
Example
`let idas = IDASFactory({ apiBaseurl: "http://localhost/api" });`
=> Allow IDASFactory settings override with only partial settings

Gandalan.IDAS.WebApi.Client.Wpf/Gandalan.IDAS.WebApi.Client.Wpf.csproj, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs, Gandalan.IDAS.WebApi.Client/GDL.IDAS.WebApi.Client.nuspec, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
- NewtonSoft.Json: https://github.com/JamesNK/Newtonsoft.Json/releases/tag/13.0.2
- PropertyChanged.Fody: https://github.com/Fody/PropertyChanged/releases/tag/4.1.0
- System.IdentityModel.Tokens.Jwt: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases
This will also fix NuGet consolidate in Backend
=> Update NuGets. Fix `IDE1006` (naming rule violation)

Gandalan.IDAS.Logging/Logging/L.cs, Gandalan.IDAS.Logging/Logging/Logger.cs, Gandalan.IDAS.WebApi.Client/Settings/ConnectHub.cs, Gandalan.IDAS.WebApi.Client/Settings/WebApiConfigurations.cs
Extended exception (single) from `TestController` before:
```
Allgemein       Fehler   19:14:19 .ctor           ExtendedStatusCodeResult: Status: BadRequest System.NullReferenceException: Test NRE exception - should be inside ExtendedStatusCodeResult
Stacktrace:    at Gandalan.IDAS.WebApi.Controllers.TestController.TestException(ExceptionType exceptionType) in C:\Gandalan\IDAS\Source\IDASWebApi\Gandalan.IDAS.WebApi.Common\Controllers\TestController.cs:line 43
```
After:
```
Allgemein       Fehler   19:15:37 .ctor           ExtendedStatusCodeResult: Status: BadRequest System.NullReferenceException: Test NRE exception - should be inside ExtendedStatusCodeResult
at Gandalan.IDAS.WebApi.Controllers.TestController.TestException(ExceptionType exceptionType) in …
```
=> Use standard exception print. Use LogConsoleDebug as public

.github/workflows/build-and-publish.yml, .github/workflows/check-NuGet-Libs.yml, .github/workflows/check-weblibs.yml, .github/workflows/publish-weblibs.yml
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Replace deprecated `set-output` with `$GITHUB_OUTPUT`

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/MailWebRoutinen.cs
Use StreamContent() instead of ByteArrayContent() for form files to allow WebApi support on both .NETFramework and .Net Core WebApi
Tested new changes on IDAS.Backend.WebApi (master) and it requires no change.
Additional changes are required on GAN-94 branch (with EFCore)
=> Use StreamContent() instead of ByteArrayContent()

.editorconfig
Disable [CA1510](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1510) warning: [ArgumentNullException.ThrowIfNull](https://learn.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull?view=net-8.0) method not available in .NET Framework 4.8
=> Disable `CA1510` warning

Gandalan.IDAS.Logging/Logging/L.cs
Example:
```
Allgemein       Fehler   15:08:22 GetItem         produktGruppenStore exception after retrieveDataIfCacheMiss (Func target: 'Gandalan.Client.Common.Flux.ProduktgruppenStore') (Time: 600,915 seconds)
URL: ProduktGruppe?includeFamilien=True&includeVarianten=True&includeUIDefs=True&maxLevel=99
CallMethod: MoveNext
StatusCode: InternalServerError
System.Threading.Tasks.TaskCanceledException: A task was canceled.
(StackTrace)
```
=> Print DetailedException in logs + new line before exception

Gandalan.IDAS.Contracts/Gandalan.IDAS.Contracts.csproj, Gandalan.IDAS.Crypto/Gandalan.IDAS.Crypto.csproj, Gandalan.IDAS.Logging/Gandalan.IDAS.Logging.csproj, Gandalan.IDAS.WebApi.Client.Wpf/Gandalan.IDAS.WebApi.Client.Wpf.csproj, Gandalan.IDAS.WebApi.Client/BusinessRoutinen/NotifyWebRoutinen.cs, Gandalan.IDAS.WebApi.Client/Gandalan.IDAS.WebApi.Client.csproj
This same as https://github.com/gandalan/idas-client-libs/pull/297, but for C#
Fixed warning introduced in 3c196878d04124b00b4b0fb239a2f6e0dcb397a3
=> `TreatWarningsAsErrors` for all build configurations

.editorconfig
Now we should have consistent sorting for all developers
=> Enable `dotnet_sort_system_directives_first`

Gandalan.IDAS.WebApi.Client/BusinessRoutinen/WebRoutinenBase.cs
We have Payload in `ApiException`, but we are not printing it yet in `L.Fehler()` (https://github.com/gandalan/idas-client-libs/blob/master/Gandalan.IDAS.Logging/Logging/L.cs#L50).
This will be helpful when debugging exceptions from **dev-support** channel
=> Print Payload in `L.Fehler()`

Gandalan.IDAS.Contracts/Token/JwtTokenService.cs, WebLibs/api/fluentRestClient.js
1. fluentRestClient: extend blob for addtional types
2. JwtTokenService: expose role/rights claims collection keys
=> fluentRestClient: extend blob for addtional types
